language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - covr
  - devtools

r_github_packages:
  - codecov/example-r

after_success:
  - Rscript -e 'library(covr);codecov()'

steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v1
  with:
    token: ${{ 9feb6a54-2c64-4da0-8207-0e7d620d0d48 }} # not required for public repos
